# Generated by Django 3.1.7 on 2021-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210507_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('bday', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default='https://github.com/SadraTghvi', max_length=200),
        ),
    ]
