# Generated by Django 3.1.7 on 2021-05-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210515_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='bday',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
