# Generated by Django 3.1.7 on 2021-05-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210517_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='subject',
        ),
    ]
